/// Flutter icons Parts
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Parts
///      fonts:
///       - asset: fonts/Parts.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Parts {
  Parts._();

  Parts();

  IconData getByName(String name)  {
    switch(name.toLowerCase()) {
      case 'chest':
        return chest;
      case 'glute':
        return glute;
      case 'back':
        return back;
      case 'arm':
        return arm;
      case 'leg':
        return leg;
      case 'shoulder':
        return shoulder;
      case 'abs':
        return abs;
      default:
        return chest;
    }
  }

  static const _kFontFam = 'Parts';
  static const String? _kFontPkg = null;

  static const IconData chest = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glute = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData abs = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leg = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shoulder = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arm = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
