/// Flutter icons Spotter
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Spotter
///      fonts:
///       - asset: fonts/Spotter.ttf
///
///
///
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class Spotter {
  Spotter._();

  static const _kFontFam = 'Spotter';
  static const String? _kFontPkg = null;

  static const IconData yoga = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ballanceBall = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aerobics = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData personalTraining = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbell2 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barbell = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barbell2 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pose = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pullup = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pullup2 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData punchingBag = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crossfit = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stretching = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stretching2 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yoga2 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData legRaise = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbell = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData pec = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData ball2 = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData stretching3 = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData crunch = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData squat2 = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData lunge = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData running = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData dip = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData dip2 = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData wallSquat = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData swimming = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData personalTrainingSquat = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData personalTrainingPushup = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData yoga3 = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData plank = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData pushup2 = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData swimming2 = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData yoga4 = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData box = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData jumpLunge = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData boxJump = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData hurdle = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData jumpRope = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData cycling = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData treadmill = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData eliptical = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData hiking = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData dumbellGroup = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData running2 = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData sprinting = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData racing = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData joggingGroup = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
   static const IconData walking = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
 }
